#encoding:utf-8
import numpy as np
#CAMERA_MODE = 7 #não utilizado
CAMERA_RESOLUCAO = (320, 240)
CAMERA_FRAMERATE = 32

LimiarBinarizacao =  30
AreaContornoLimiteMin = 1000 #experimental
KERNEL_GAUSSIAN_BLUR = (21,21)
QUANTIDADE_ITERACOES_DILATE = 2

#HEIGTH/WIDTH
ASPECT_RATIO_MAX = 0.5

KERNEL_OPENING = np.ones((5,5),np.uint8)

ROI_X1 = 0
ROI_Y1 = CAMERA_RESOLUCAO[1]//3
ROI_X2 = CAMERA_RESOLUCAO[0]
ROI_Y2 = CAMERA_RESOLUCAO[1]

ROI_WIDTH = ROI_X2 - ROI_X1
ROI_HEIGTH = ROI_Y2 - ROI_Y1

DATA_PATH = './'
ARQUIVO_CSV = 'teste.csv'
ARQUIVO_VIDEO = 'output.avi'
ARQUIVO_GRAFICO = 'grafico.png'

MEDIA_MOVEL_POSICAO_SIZE = 5
MEDIA_MOVEL_VALOR_POSICAO_INICIAL = ROI_WIDTH//2

MEDIA_MOVEL_ANGULO_SIZE = 5
MEDIA_MOVEL_VALOR_ANGULO_INICIAL = 90.0

MEDIA_MOVEL_POSICAOY_SIZE = 5
MEDIA_MOVEL_VALOR_POSICAOY_INICIAL = ROI_HEIGTH//2

x_target = ROI_WIDTH//2

THETA_MAX = 120
THETA_MIN = 60

Kp_turn = 20
Kp_line = 10
Kd = 0
Ki = 0

mean_h = 0